In [2]:
import torch
import numpy as np

In [12]:
import torch

x = torch.tensor([[1., 2., 3.]
                  #    , [1., 2., 3.]
                  ],
                 requires_grad=True)
w = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

b = torch.tensor([11., 22.])

y = torch.tensor([[115., 222.]], requires_grad=True)

# Создание тензоров для входных данных, весов и смещения
#x = torch.randn(1, 3) # 10 примеров по 5 признаков
#w = torch.randn(2, 3) # 5 признаков, 3 выходных нейрона
#b = torch.randn(2) # смещение для каждого выходного нейрона

# Определение линейной функции со смещением
linear = torch.nn.Linear(3, 2)  # 5 входных признаков, 3 выходных нейрона
linear.weight.data = w
linear.bias.data = b

# Определение функции потерь
loss_fn = torch.nn.MSELoss()

relu = torch.nn.ReLU()

# Расчет функции потерь и градиента
y_pred = relu(linear(x))  # Применение линейной функции

print(y_pred)

loss = loss_fn(y_pred, y)  # Расчет функции потерь
loss.backward()  # Расчет градиента

# Получение градиента по весам и смещению
dw = linear.weight.grad
db = linear.bias.grad

print(x.grad)
print(y.grad)
print(dw)
print(db)

tensor([[25., 54.]], grad_fn=<ReluBackward0>)
tensor([[ -762., -1020., -1278.]])
tensor([[ 90., 168.]])
tensor([[ -90., -180., -270.],
        [-168., -336., -504.]])
tensor([ -90., -168.])


In [3]:

cel = torch.nn.CrossEntropyLoss(reduction="sum")
b = torch.tensor([[1., 2., 3.],
                  [10., 10., 5.]], requires_grad=True)

t = torch.tensor([[0, 0, 1.], [1., 0, 0]], requires_grad=True)

r = torch.nn.ReLU()
t = r(t)

loss2 = cel(b, t)
loss2.backward()

print(loss2)
print(b.grad)

tensor(1.1041, grad_fn=<NegBackward0>)
tensor([[ 0.0900,  0.2447, -0.3348],
        [-0.5017,  0.4983,  0.0034]])


In [25]:
import numpy as np;
import torch

k = np.array(
    [[
        1, 0, -1,
        2, 0, -2,
        1, 0, -1
    ],
        [
            1, 3, -1,
            2, 44, -2,
            1, 2, -1
        ],

        [
            3, 4, 5,
            6, 7, 8,
            9, 10, 11
        ],
        [11, 23, 42,
         2, 2, 2,
         1, 2, 3]
    ]).reshape(2, 2, 3, 3).astype(np.float32)

x = np.array(
    [[
        [1, 1, 1, 2, 3],
        [1, 1, 1, 2, 3],
        [1, 1, 1, 2, 3],
        [2, 2, 2, 2, 3],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]
    ],

        [
            [1, 1, 5, 2, 3],
            [1, 1, 6, 2, 3],
            [1, 1, 7, 2, 3],
            [2, 2, 8, 2, 3],
            [3, 3, 9, 3, 3],
            [4, 4, 0, 4, 4]
        ]

    ]).reshape(1, 2, 6, 5).astype(np.float32)


conv = torch.nn.Conv2d(
    in_channels=2,
    out_channels=2,
    kernel_size=3,
    bias=False,
    stride=1,
    padding_mode='zeros',
    padding=0
)


x_tensor = torch.from_numpy(x)
x_tensor.requires_grad = True
conv.weight = torch.nn.Parameter(torch.from_numpy(k))
conv.weight.requires_grad = True
out = conv(x_tensor)
loss = out.sum()
loss.backward()

#print(out)
#print(conv.weight.grad)
print(x_tensor.grad)
#print(conv1(x1_tensor))
# print(conv1(x2_tensor))

tensor([[[[  4.,   8.,  12.,   8.,   4.],
          [ 12.,  23.,  33.,  21.,  10.],
          [ 22.,  43.,  63.,  41.,  20.],
          [ 22.,  43.,  63.,  41.,  20.],
          [ 18.,  35.,  51.,  33.,  16.],
          [ 10.,  20.,  30.,  20.,  10.]],

         [[ 12.,  38.,  79.,  67.,  41.],
          [ 16.,  88., 129., 113.,  41.],
          [ 18.,  94., 137., 119.,  43.],
          [ 18.,  94., 137., 119.,  43.],
          [  6.,  56.,  58.,  52.,   2.],
          [  2.,   6.,   8.,   6.,   2.]]]])
