In [1]:
import torch
import numpy as np

In [69]:
import torch

x = torch.tensor([[1., 2., 3.]], requires_grad=True)
w = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

b = torch.tensor([11., 22.])

y = torch.tensor([[115., 222.]], requires_grad=True)

# Создание тензоров для входных данных, весов и смещения
#x = torch.randn(1, 3) # 10 примеров по 5 признаков
#w = torch.randn(2, 3) # 5 признаков, 3 выходных нейрона
#b = torch.randn(2) # смещение для каждого выходного нейрона

# Определение линейной функции со смещением
linear = torch.nn.Linear(3, 2) # 5 входных признаков, 3 выходных нейрона
linear.weight.data = w
linear.bias.data = b

# Определение функции потерь
loss_fn = torch.nn.MSELoss()

# Расчет функции потерь и градиента
y_pred = linear(x) # Применение линейной функции
loss = loss_fn(y_pred, y) # Расчет функции потерь
loss.backward() # Расчет градиента

# Получение градиента по весам и смещению
dw = linear.weight.grad
db = linear.bias.grad

print(x.grad)
print(y.grad)
print(dw)
print(db)

tensor([[ -762., -1020., -1278.]])
tensor([[ 90., 168.]])
tensor([[ -90., -180., -270.],
        [-168., -336., -504.]])
tensor([ -90., -168.])
